from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any

class SearchHit(BaseModel):
    """Defines the structure for a single search result hit."""
    id: str = Field(description="Unique identifier for the search hit")
    title: str = Field(description="Title of the document or chunk")
    content: str = Field(description="Content of the document or chunk")
    url: str = Field(description="URL of the document")

    score: float = Field(description="Relevance score of the search hit")

    metadata: Dict[str, Any] = Field(default_factory=dict, 
                                     description="Additional metadata for the search hit"
                                     )

class GeneratorResponse(BaseModel):
    """Defines the structure for the overall search response."""
    query: str = Field(description="The original search query")
    summary: Optional[str] = Field(description="Optional summary of the search results generated by the LLM")
    results: List[SearchHit] = Field(description="List of search results")
    total: int = Field(description="Total number of search results")
    duration_ms: float = Field(description="Time taken to perform the search in milliseconds")   

    model_config=ConfigDict(
        json_schema_extra={
            "examples": {
                "query": "Tình hình giá vàng hôm nay?",
                "summary": "Theo các nguồn tin, giá vàng hôm nay đã tăng nhẹ...",
                "results": [
                    {
                        "id": "123e4567-e89b-12d3-a456-426614174000",
                        "title": "Giá vàng SJC tăng 500k",
                        "content": "Sáng nay, giá vàng SJC trong nước đã tăng...",
                        "url": "https://example.com/gia-vang",
                        "score": 0.95,
                        "metadata": {
                            "publication_date": "2024-05-01",
                            "authors": ["Alice Smith", "Bob Johnson"]
                        }
                    },
                    {
                        "id": "67890",
                        "title": "Improving Model Efficiency in Computer Vision",
                        "content": "This study explores methods to reduce the computational cost of computer vision models while maintaining accuracy.",
                        "url": "https://example.com/cv-paper",
                        "score": 0.90,
                        "metadata": {
                            "publication_date": "2024-04-15",
                            "authors": ["Carol Lee", "David Kim"]
                        }
                    }
                ],
                "total": 2,
                "duration_ms": 150.5
            }
        }

    )